DROP TABLE IF EXISTS blocks;
ALTER TABLE comments DROP COLUMN IF EXISTS visibility_reason;
ALTER TABLE comments DROP COLUMN IF EXISTS moderation_case_id;
ALTER TABLE comments DROP COLUMN IF EXISTS delete_reason;
ALTER TABLE comments DROP COLUMN IF EXISTS deleted_by;
ALTER TABLE posts DROP COLUMN IF EXISTS visibility_reason;
ALTER TABLE posts DROP COLUMN IF EXISTS moderation_case_id;
ALTER TABLE posts DROP COLUMN IF EXISTS delete_reason;
ALTER TABLE posts DROP COLUMN IF EXISTS deleted_by;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS moderation_actions;
DROP TABLE IF EXISTS moderation_cases;
DROP TABLE IF EXISTS reports;
