DROP TRIGGER IF EXISTS admin_logs_no_update ON admin_logs;
DROP FUNCTION IF EXISTS prevent_admin_log_mutation();
DROP TRIGGER IF EXISTS comments_content_rules ON comments;
DROP TRIGGER IF EXISTS posts_content_rules ON posts;
DROP FUNCTION IF EXISTS apply_comment_content_rules();
DROP FUNCTION IF EXISTS apply_forum_content_rules();
DROP TABLE IF EXISTS admin_logs;
DROP TABLE IF EXISTS admin_log_chain;
ALTER TABLE moderation_actions DROP COLUMN IF EXISTS ends_at;
ALTER TABLE moderation_actions DROP COLUMN IF EXISTS starts_at;
ALTER TABLE moderation_actions DROP COLUMN IF EXISTS duration_days;
ALTER TABLE posts DROP CONSTRAINT IF EXISTS posts_post_status_check;
ALTER TABLE posts DROP COLUMN IF EXISTS post_status;
DROP TABLE IF EXISTS risk_events;
DROP TABLE IF EXISTS login_devices;
DROP TABLE IF EXISTS admin_invites;
DROP TABLE IF EXISTS restrictions;
DROP TABLE IF EXISTS bans;
DROP TABLE IF EXISTS guest_sessions;
DROP TABLE IF EXISTS email_codes;
DROP INDEX IF EXISTS users_email_unique_idx;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_account_type_check;
ALTER TABLE users DROP COLUMN IF EXISTS account_type;
ALTER TABLE users DROP COLUMN IF EXISTS email_verified_at;
ALTER TABLE users DROP COLUMN IF EXISTS email_verified;
ALTER TABLE users DROP COLUMN IF EXISTS email;
