import { test, expect } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";

// 该用例连接隔离 API、worker、媒体存储和测试数据库，CI 作为独立步骤执行。
test("真实论坛旅程：游客、浏览、图片评论、回复定位和原身份注册", async ({ page, request }) => {
  test.skip(process.env.LUNTAN_LIVE_JOURNEY !== "1", "需要独立的本地 API 与 PostgreSQL");
  test.setTimeout(150000);
  page.setDefaultTimeout(15000);
  const databaseUrl = process.env.DATABASE_URL || "";
  const databaseHost = new URL(databaseUrl).hostname;
  expect(["127.0.0.1", "localhost", "postgres"]).toContain(databaseHost);
  expect(new URL(databaseUrl).pathname).toMatch(/_test$/);
  const sql = (statement: string) => execFileSync(process.env.PSQL_BIN || "psql", ["-X", "-t", "-A", "-v", "ON_ERROR_STOP=1", "-d", databaseUrl], { encoding: "utf8", input: statement, env: { ...process.env, PGCLIENTENCODING: "UTF8" } }).trim();
  const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
  const suffix = randomUUID();
  const categoryId = `journey-cat-${suffix}`;
  const markerId = `journey-marker-${suffix}`;
  // 先以随机只读标记核实代理确实指向测试库，再发送任何注册或上传请求。
  sql(`INSERT INTO community_categories (id,name,slug) VALUES (${quote(categoryId)},'端到端测试',${quote(categoryId)});
    INSERT INTO communities (id,category_id,slug,name,status) VALUES (${quote(markerId)},${quote(categoryId)},${quote(markerId)},${quote(markerId)},'active');`);
  const marker = await request.get(`/api/v1/communities/${markerId}`);
  expect(marker.ok()).toBeTruthy();
  expect((await marker.json()).id).toBe(markerId);
  const webOrigin = process.env.LUNTAN_JOURNEY_WEB_ORIGIN;
  if (webOrigin) {
    // 可复用已部署的前端，但所有业务请求强制转入本地测试 API，不在生产库写入测试数据。
    const apiOrigin = process.env.PLAYWRIGHT_TEST_BASE_URL || "";
    expect(new URL(apiOrigin).hostname).toBe("127.0.0.1");
    await page.route("**/api/v1/**", async (route) => {
      const url = new URL(route.request().url());
      const response = await route.fetch({ url: new URL(url.pathname + url.search, apiOrigin).toString() });
      await route.fulfill({ response });
    });
  }
  const navigate = (route: string) => page.goto(webOrigin ? new URL(route, webOrigin).toString() : route, { waitUntil: "domcontentloaded", timeout: 30000 });
  const authorResponse = await request.post("/api/v1/auth/register", { data: { username: `journey_${suffix}`, password: "TestPassword123!", nickname: "旅程楼主" } });
  expect(authorResponse.status()).toBe(201);
  const author = await authorResponse.json();
  const auth = { Authorization: `Bearer ${author.access_token}` };
  const photoPath = path.resolve("../assets/images/store/badge.jpg");
  const photo = readFileSync(photoPath);
  const checksum = createHash("sha256").update(photo).digest("hex");
  const uploadToken = await request.post("/api/v1/media/upload-token", { headers: auth, data: { file_name: "badge.jpg", mime_type: "image/jpeg", width: 0, height: 0, size: photo.length, sha256: checksum } });
  expect(uploadToken.status()).toBe(201);
  const upload = await uploadToken.json();
  expect((await request.put(upload.upload_url, { data: photo, headers: { "Content-Type": "image/jpeg" } })).ok()).toBeTruthy();
  expect((await request.post(`/api/v1/media/${upload.media_id}/complete`, { headers: auth, data: { size: photo.length, sha256: checksum } })).ok()).toBeTruthy();
  // complete 只确认上传，等待 worker 生成变体后再打开页面。
  await expect.poll(() => sql(`SELECT count(*) FROM media_variants WHERE media_id=${quote(upload.media_id)} AND variant='detail' AND status='ready'`), { timeout: 30000 }).toBe("1");
  const postId = `journey-post-${suffix}`;
  const title = `真实论坛旅程 ${suffix}`;
  sql(`INSERT INTO communities (id,category_id,slug,name,status) VALUES ('community-campus',${quote(categoryId)},'journey-campus','校园','active') ON CONFLICT (id) DO NOTHING;
    INSERT INTO posts (id,author_id,community_id,type,publication_status,moderation_status,title,content,published_at)
    VALUES (${quote(postId)},${quote(author.user.id)},'community-campus','normal','published','normal',${quote(title)},'包含真实图片和评论的旅程测试',now());
    INSERT INTO post_media (post_id,media_id,sort_order) VALUES (${quote(postId)},${quote(upload.media_id)},0);`);

  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const guestResponse = page.waitForResponse((response) => response.url().endsWith("/api/v1/auth/guest") && response.request().method() === "POST");
  await navigate("/");
  const guest = await (await guestResponse).json();
  expect(guest.user.account_type).toBe("guest");
  const guestId = guest.user.id;
  const viewResponse = page.waitForResponse((response) => response.url().endsWith(`/posts/${postId}/view`));
  await page.getByRole("heading", { name: title, exact: true }).first().click();
  expect((await (await viewResponse).json()).recorded).toBe(true);
  expect(sql(`SELECT view_count FROM posts WHERE id=${quote(postId)}`)).toBe("1");
  await page.locator(".detail-gallery img").first().click();
  await expect(page.getByRole("dialog", { name: "图片查看器" })).toBeVisible();
  await expect.poll(() => page.locator(".gallery-main-image").evaluateAll((images) => images.some((image) => (image as HTMLImageElement).naturalWidth > 0)), { timeout: 20000 }).toBe(true);
  await page.getByRole("button", { name: "关闭查看器" }).click();
  const composer = page.locator("form").filter({ has: page.getByRole("button", { name: "发布回复", exact: true }) });
  await composer.locator("textarea").fill("游客评论，注册后保留");
  const commentResponse = page.waitForResponse((response) => response.url().endsWith(`/posts/${postId}/comments`) && response.request().method() === "POST");
  await composer.getByRole("button", { name: "发布回复", exact: true }).click();
  const createdResponse = await commentResponse;
  expect(createdResponse.status()).toBe(201);
  const comment = await createdResponse.json();
  const commentNode = page.locator(`#comment-${comment.id}`);
  await expect(commentNode).toContainText("游客评论，注册后保留");
  const notes = await request.get("/api/v1/notifications?category=interaction", { headers: auth });
  expect((await notes.json()).items.some((item: { type: string; target_id: string }) => item.type === "comment.created" && item.target_id === postId)).toBe(true);
  const replyResponse = await request.post(`/api/v1/comments/${comment.id}/replies`, { headers: { ...auth, "Idempotency-Key": randomUUID() }, data: { content: "楼主回复游客，准确定位这一条" } });
  expect(replyResponse.status()).toBe(201);
  const reply = await replyResponse.json();
  await navigate("/notifications");
  const notification = page.locator(`a[href="/post/${postId}?comment=${comment.id}&reply=${reply.id}"]`);
  await notification.click();
  const focusedReply = page.locator(`.comment-reply-modal #comment-${reply.id}`);
  await expect(focusedReply).toBeVisible();
  await expect(focusedReply).toHaveClass(/comment-highlight/);
  await page.getByRole("button", { name: "关闭回复", exact: true }).click();

  await navigate("/login?mode=register");
  await page.getByPlaceholder("请输入邮箱地址").fill(`journey-${suffix}@example.com`);
  await page.getByPlaceholder("至少 8 位密码").fill("TestPassword123!");
  await page.getByPlaceholder("再次输入密码").fill("TestPassword123!");
  const registrationResponse = page.waitForResponse((response) => response.url().includes("/auth/register") && response.request().method() === "POST");
  await page.getByRole("button", { name: "注册并进入社区", exact: true }).click();
  const registeredResponse = await registrationResponse;
  expect(registeredResponse.ok()).toBeTruthy();
  const registered = await registeredResponse.json();
  expect(registered.user.id).toBe(guestId);
  expect(registered.user.account_type).toBe("email");
  expect(sql(`SELECT author_id FROM comments WHERE id=${quote(comment.id)}`)).toBe(guestId);
  expect(sql(`SELECT COUNT(*) FROM comment_media WHERE comment_id=${quote(comment.id)}`)).toBe("0");
  expect(sql(`SELECT COUNT(*) FROM post_view_events WHERE post_id=${quote(postId)} AND viewer_key=${quote("u:" + guestId)}`)).toBe("1");
  await navigate(`/post/${postId}?comment=${comment.id}`);
  await expect(page.locator(`#comment-${comment.id}`)).toContainText("游客评论，注册后保留");
  const imageComposer = page.locator("form").filter({ has: page.getByRole("button", { name: "发布回复", exact: true }) });
  await imageComposer.locator("textarea").fill("正式账号自己发图并查看");
  await imageComposer.locator('input[type="file"]').setInputFiles(photoPath);
  const imageResponse = page.waitForResponse((response) => response.url().endsWith(`/posts/${postId}/comments`) && response.request().method() === "POST");
  await imageComposer.getByRole("button", { name: "发布回复", exact: true }).click();
  const imageComment = await (await imageResponse).json();
  const imageNode = page.locator(`#comment-${imageComment.id} .comment-media-grid img`);
  await expect.poll(() => imageNode.evaluateAll((images) => images.some((image) => (image as HTMLImageElement).naturalWidth > 0)), { timeout: 20000 }).toBe(true);
  await imageNode.click();
  await expect.poll(() => page.locator(".gallery-main-image").evaluateAll((images) => images.some((image) => (image as HTMLImageElement).naturalWidth > 0)), { timeout: 20000 }).toBe(true);
  if (process.env.LUNTAN_QA_SCREENSHOT_DIR) await page.screenshot({ path: path.join(process.env.LUNTAN_QA_SCREENSHOT_DIR, "own-comment-gallery.png"), fullPage: false });
  await page.getByRole("button", { name: "关闭查看器" }).click();
  // 同一个正式账号继续走真实兑换、订单页和积分返还，不使用生产积分。
  const productId = `journey-product-${suffix}`;
  const productName = `旅程测试徽章 ${suffix.slice(0, 8)}`;
  sql(`UPDATE users SET points_balance=100 WHERE id=${quote(guestId)};
    INSERT INTO store_products (id,name,points,stock_total) VALUES (${quote(productId)},${quote(productName)},60,5);
    INSERT INTO user_roles (id,user_id,role_id) VALUES (${quote(`journey-role-${suffix}`)},${quote(author.user.id)},'role-super-admin');`);
  await navigate("/points");
  await expect(page.locator(".points-hero-number")).toHaveText("100");
  await page.locator(".store-product-card").filter({ hasText: productName }).getByRole("button", { name: "申请兑换" }).click();
  const orderResponse = page.waitForResponse((response) => response.url().endsWith("/store/orders") && response.request().method() === "POST");
  await page.getByRole("button", { name: "提交申请" }).click();
  const order = await (await orderResponse).json();
  expect(order.id).toBeTruthy();
  await expect(page.locator(`#order-${order.id}`)).toContainText("审核中");
  expect(sql(`SELECT points_balance FROM users WHERE id=${quote(guestId)}`)).toBe("100");
  const approval = await request.post(`/api/v1/admin/store/orders/${order.id}/review`, { headers: auth, data: { decision: "approve" } });
  expect(approval.status()).toBe(200);
  expect(sql(`SELECT points_balance FROM users WHERE id=${quote(guestId)}`)).toBe("40");
  await navigate(`/points?tab=orders&order=${order.id}`);
  const shippingDialog = page.getByRole("dialog", { name: "填写收货地址" });
  await expect(shippingDialog).toBeVisible();
  await shippingDialog.getByRole("button", { name: "取消", exact: true }).click();
  await expect(shippingDialog).toBeHidden();
  await page.locator(`#order-${order.id}`).getByRole("button", { name: "取消与售后" }).click();
  const aftercare = page.getByRole("dialog", { name: "取消与售后" });
  await aftercare.locator("textarea").fill("本地测试取消兑换");
  await aftercare.getByRole("button", { name: "取消订单并返还已扣积分" }).click();
  await expect(page.locator(`#order-${order.id}`)).toContainText("已取消");
  await expect(page.locator(".points-hero-number")).toHaveText("100");
  expect(sql(`SELECT stock_reserved FROM store_products WHERE id=${quote(productId)}`)).toBe("0");
  if (process.env.LUNTAN_QA_SCREENSHOT_DIR) await page.screenshot({ path: path.join(process.env.LUNTAN_QA_SCREENSHOT_DIR, "store-cancelled-desktop.png"), fullPage: false });
  expect(errors).toEqual([]);
});
